name: Django Backend CI

on:
  push:
    paths:
      - 'Backend/**'
  pull_request:
    paths:
      - 'Backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd Backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django tests
      env:
        DB_NAME: test_db
        DB_USER: user
        DB_PASSWORD: password
        DB_HOST: localhost
        DB_PORT: 5432
      run: |
        cd Backend
        python manage.py test


