name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend  # All commands run from Backend folder

    steps:
      - name: Checkout Database branch
        uses: actions/checkout@v4
        with:
          ref: Database  # Checkout the branch that contains the backend

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv
          pip install django-cors-headers mysqlclient
      - name: Install system dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y default-libmysqlclient-dev build-essential


      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: mozuma.settings  
        run: |
          python manage.py test
