name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mozuma_db
          MYSQL_USER: mozuma_user
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    defaults:
      run:
        working-directory: Backend   # because manage.py is inside Backend/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # 👈 removed `ref: Database`

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y default-libmysqlclient-dev build-essential

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv django-cors-headers mysqlclient

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h"127.0.0.1" --silent; do
            sleep 2
          done

      - name: Grant all privileges to mozuma_user
        run: |
          mysql -h127.0.0.1 -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'mozuma_user'@'%'; FLUSH PRIVILEGES;"

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: mozuma.settings
          db_password: testpass
          db_host: 127.0.0.1
          db_port: 3306
        run: |
          python manage.py test
