name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:   # 👈 services should be inside the job, not outside
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mozuma_db
          MYSQL_USER: mozuma_user
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    defaults:
      run:
        working-directory: Backend  # All commands run from Backend folder

    steps:
      - name: Checkout Database branch
        uses: actions/checkout@v4
        with:
          ref: Database  # Checkout the branch that contains the backend

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv
          pip install django-cors-headers mysqlclient

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y default-libmysqlclient-dev build-essential

          - name: Wait for MySQL to be ready
            run: |
            until mysqladmin ping -h"127.0.0.1" --silent; do
            sleep 2
            done

      - name: Grant test DB privileges
        run: |
             mysql -h127.0.0.1 -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'mozuma_user'@'%'; FLUSH PRIVILEGES;"

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: mozuma.settings
          db_password: testpass   # 👈 matches MYSQL_PASSWORD above
          db_host: 127.0.0.1      # force TCP
          db_port: 3306
        run: |
          python manage.py test
