name: Unified Frontend & Backend CI/CD

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports: [3306:3306]
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Backend Setup & Test (Python/Django)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Backend Dependencies
        if: contains(steps.checkout.outputs.path, 'Backend/requirements.txt')
        run: pip install -r ./Backend/requirements.txt

      - name: Run Django Tests
        if: contains(steps.checkout.outputs.path, 'Backend/manage.py')
        run: |
          cd Backend
          python manage.py test

      # Frontend Setup & Build (Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        if: contains(steps.checkout.outputs.path, 'Frontend/package.json')
        run: |
          cd Frontend
          npm install

      - name: Build Frontend
        if: contains(steps.checkout.outputs.path, 'Frontend/package.json')
        run: |
          cd Frontend
          npm run build
